config:
  target: 'http://40.74.14.32/scc2021-52676-1.0/rest'
#  target: 'http://localhost:8080/scc2122-backend/rest'
  http:
    timeout: 10
  plugins:
    metrics-by-endpoint: {}
  processor: "./test-utils.js"
  variables:
     metricsProcessEndpoint : "myProcessEndpoint"  # function used to aggregate endpoints for statistics
  phases:
  - name: "Create channels"    # Create channels
    duration: 1
    arrivalCount: 1

scenarios:
  - name: 'Create channels'
    weight: 1
    flow:
      - loop:                            # let's create 10 public channels - loop ... count
        - function: "selectUserSkewed"
        - post:                          # First: login as a user
            url: "/users/auth"
            headers:
              Content-Type: application/json
            json:
              id: "{{ user }}"
              password: "{{ pwd }}"
        - function: "genNewChannel"
        - post:                          # Create channel
            url: "/channels/create"
            headers:
              Content-Type: application/json
              Accept: application/json
            json:
              name: "{{ channelName }}"
              idOwner: "{{ user }}"
              isPriv: false
              idUsers: []
            capture:                     # Capturing channel id
              - json: $.id
                as: "channelId"
        - loop:                          # Let's add 20 users to the channel
          - function: "selectUserSkewed"
          - post:                         
              url: "/users/auth"
              headers:
                Content-Type: application/json
              json:
                id: "{{ user }}"
                password: "{{ pwd }}"
          - post:                          # Subscribe     
              url: "/users/{{ user }}/subscribe/{{ channelId }}"
          count: 20
        count: 10   
      - loop:                            # let's create 45 private channels - loop ... count
        - function: "selectUserSkewed"
        - post:                          # First: login as a user
            url: "/users/auth"
            headers:
              Content-Type: application/json
            json:
              id: "{{ user }}"
              password: "{{ pwd }}"
        - function: "genNewChannel"
        - post:                          # Create channel
            url: "/channels/create"
            headers:
              Content-Type: application/json
              Accept: application/json
            json:
              name: "{{ channelName }}"
              idOwner: "{{ user }}"
              isPriv: true
              idUsers: []
            capture:                     # Capturing channel id
              - json: $.id
                as: "channelId"
        - loop:                          # Let's add 10 users to the channel
          - function: "selectUserSkewed"
          - post:                          # Add user to private channel   
              url: "/channels/{{ channelId }}/add/{{ user }}"
          count: 10
        count: 45
